import { index, int, json, mysqlEnum, mysqlTable, text, timestamp, varchar } from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 * Extend this file with additional tables as your product grows.
 * Columns use camelCase to match both database fields and generated types.
 */
export const users = mysqlTable("users", {
  /**
   * Surrogate primary key. Auto-incremented numeric value managed by the database.
   * Use this for relations between tables.
   */
  id: int("id").autoincrement().primaryKey(),
  /** Manus OAuth identifier (openId) returned from the OAuth callback. Unique per user. */
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/** A versioned execution of the satellite-to-subsurface reconstruction pipeline. */
export const oceanRuns = mysqlTable("ocean_runs", {
  id: varchar("id", { length: 64 }).primaryKey(),
  status: mysqlEnum("status", ["queued", "processing", "completed", "degraded", "failed"]).notNull(),
  asOf: timestamp("as_of").notNull(),
  regionName: varchar("region_name", { length: 120 }).notNull(),
  sourceManifestKey: varchar("source_manifest_key", { length: 512 }).notNull(),
  datasetVersion: varchar("dataset_version", { length: 120 }).notNull(),
  modelVersion: varchar("model_version", { length: 120 }).notNull(),
  codeVersion: varchar("code_version", { length: 120 }).notNull(),
  confidence: mysqlEnum("confidence", ["high", "moderate", "limited", "insufficient"]).notNull(),
  fallbackMode: mysqlEnum("fallback_mode", ["none", "selective_climatology", "full_climatology", "human_review"]).notNull(),
  scheduleCronTaskUid: varchar("schedule_cron_task_uid", { length: 65 }),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  completedAt: timestamp("completed_at"),
}, table => [
  index("ocean_runs_as_of_idx").on(table.asOf),
  index("ocean_runs_schedule_task_idx").on(table.scheduleCronTaskUid),
]);

/** The project-level owner of the recurring North Indian Ocean scene-refresh job. */
export const pipelineConfigs = mysqlTable("pipeline_configs", {
  id: varchar("id", { length: 64 }).primaryKey(),
  name: varchar("name", { length: 120 }).notNull(),
  regionName: varchar("region_name", { length: 120 }).notNull(),
  cronExpression: varchar("cron_expression", { length: 64 }).notNull(),
  scheduleCronTaskUid: varchar("schedule_cron_task_uid", { length: 65 }),
  enabled: int("enabled").notNull().default(0),
  dataSourceStatus: mysqlEnum("data_source_status", ["unconfigured", "ready", "degraded"]).notNull().default("unconfigured"),
  modelEndpointStatus: mysqlEnum("model_endpoint_status", ["unconfigured", "ready", "degraded"]).notNull().default("unconfigured"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
}, table => [
  index("pipeline_configs_schedule_task_idx").on(table.scheduleCronTaskUid),
]);

/** Immutable reference metadata for raw subsets, layers, models, extracts, and reproducibility bundles. */
export const artifactRefs = mysqlTable("artifact_refs", {
  id: varchar("id", { length: 64 }).primaryKey(),
  runId: varchar("run_id", { length: 64 }).notNull(),
  kind: mysqlEnum("kind", ["source_subset", "opencv_layer", "model_artifact", "validation_extract", "reproducibility_bundle", "evidence_snapshot"]).notNull(),
  objectKey: varchar("object_key", { length: 512 }).notNull(),
  publicUrl: varchar("public_url", { length: 1024 }),
  sha256: varchar("sha256", { length: 64 }).notNull(),
  contentType: varchar("content_type", { length: 160 }).notNull(),
  byteSize: int("byte_size").notNull(),
  provenance: json("provenance").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
}, table => [
  index("artifact_refs_run_idx").on(table.runId),
  index("artifact_refs_kind_idx").on(table.kind),
]);

/** An auditable perception-decision-action record generated by the QA workflow. */
export const qaTraces = mysqlTable("qa_traces", {
  id: varchar("id", { length: 64 }).primaryKey(),
  runId: varchar("run_id", { length: 64 }).notNull(),
  sequence: int("sequence").notNull(),
  triggerType: mysqlEnum("trigger_type", ["cloud_gap", "front_discontinuity", "uncertainty_cluster", "validation_divergence"]).notNull(),
  action: mysqlEnum("action", ["reprocess_inpainting", "selective_climatology", "request_human_review", "accept_scene"]).notNull(),
  rationale: text("rationale").notNull(),
  evidence: json("evidence").notNull(),
  beforeMetrics: json("before_metrics").notNull(),
  afterMetrics: json("after_metrics"),
  humanReviewer: varchar("human_reviewer", { length: 128 }),
  state: mysqlEnum("state", ["detected", "actioned", "accepted", "escalated"]).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
}, table => [
  index("qa_traces_run_idx").on(table.runId),
]);

/** A held-out Argo profile matched to a completed scene for independent performance assessment. */
export const argoCollocations = mysqlTable("argo_collocations", {
  id: varchar("id", { length: 64 }).primaryKey(),
  runId: varchar("run_id", { length: 64 }).notNull(),
  floatId: varchar("float_id", { length: 64 }).notNull(),
  observedAt: timestamp("observed_at").notNull(),
  latitude: varchar("latitude", { length: 32 }).notNull(),
  longitude: varchar("longitude", { length: 32 }).notNull(),
  overallRmse: varchar("overall_rmse", { length: 32 }).notNull(),
  overallBias: varchar("overall_bias", { length: 32 }).notNull(),
  correlation: varchar("correlation", { length: 32 }).notNull(),
  metricsByDepthBand: json("metrics_by_depth_band").notNull(),
  artifactId: varchar("artifact_id", { length: 64 }).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
}, table => [
  index("argo_collocations_run_idx").on(table.runId),
  index("argo_collocations_float_idx").on(table.floatId),
]);

/** A bounded region and thresholds owned by the project for conservative operational alerts. */
export const monitoredRegions = mysqlTable("monitored_regions", {
  id: varchar("id", { length: 64 }).primaryKey(),
  name: varchar("name", { length: 120 }).notNull(),
  bounds: json("bounds").notNull(),
  heatFuelThreshold: varchar("heat_fuel_threshold", { length: 32 }).notNull(),
  uncertaintyThreshold: varchar("uncertainty_threshold", { length: 32 }).notNull(),
  active: int("active").notNull().default(1),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
});

/** Small, UI-ready summaries for a completed run; raw source and artifact bytes stay in object storage. */
export const oceanRunPayloads = mysqlTable("ocean_run_payloads", {
  id: varchar("id", { length: 64 }).primaryKey(),
  runId: varchar("run_id", { length: 64 }).notNull().unique(),
  reconstructionProfile: json("reconstruction_profile").notNull(),
  uncertaintyProfile: json("uncertainty_profile").notNull(),
  decision: json("decision").notNull(),
  validationSummary: json("validation_summary").notNull(),
  qaSnapshot: json("qa_snapshot").notNull(),
  display: json("display").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
}, table => [
  index("ocean_run_payloads_run_idx").on(table.runId),
]);

/** Delivery and evidence metadata for every owner-facing threshold notification. */
export const thresholdAlerts = mysqlTable("threshold_alerts", {
  id: varchar("id", { length: 64 }).primaryKey(),
  runId: varchar("run_id", { length: 64 }).notNull(),
  monitoredRegionId: varchar("monitored_region_id", { length: 64 }).notNull(),
  type: mysqlEnum("type", ["heat_fuel", "uncertainty", "combined"]).notNull(),
  severity: mysqlEnum("severity", ["watch", "review", "high"]).notNull(),
  evidenceArtifactId: varchar("evidence_artifact_id", { length: 64 }).notNull(),
  qaTraceId: varchar("qa_trace_id", { length: 64 }).notNull(),
  deliveryState: mysqlEnum("delivery_state", ["pending", "delivered", "failed"]).notNull(),
  deliveredAt: timestamp("delivered_at"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
}, table => [
  index("threshold_alerts_run_idx").on(table.runId),
  index("threshold_alerts_region_idx").on(table.monitoredRegionId),
]);

export type OceanRun = typeof oceanRuns.$inferSelect;
export type NewOceanRun = typeof oceanRuns.$inferInsert;
export type PipelineConfig = typeof pipelineConfigs.$inferSelect;
export type ArtifactRef = typeof artifactRefs.$inferSelect;
export type OceanRunPayload = typeof oceanRunPayloads.$inferSelect;
export type QaTrace = typeof qaTraces.$inferSelect;
export type ArgoCollocation = typeof argoCollocations.$inferSelect;
export type MonitoredRegion = typeof monitoredRegions.$inferSelect;
export type ThresholdAlert = typeof thresholdAlerts.$inferSelect;
